### ISSUE TITLE
Связать логику игрока с интерфейсом

### ISSUE THREAD

**Issue by Ludwintor** [Ludwintor/BestGameProject#17]
Отображать золото, энергию, предметы и усиления игрока на интерфейсе. Если некоторая логика недоступна (не реализована), то предположить, что входит в этот интерфейс (например, для золота это просто текст, который преобразует число в текст в выведет на экран)

**Comment by Ludwintor** [comment]
@AbysssShutter нет ничего на ветке, то что ты показывал - не весь функционал

**Comment by DiedInFire** [comment]
Пардон, забыл залить на гит
